version: '3'
services: 
    app:
        container_name: huda-server
        restart: always
        build: .
        ports: 
            - "8048:8048"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"